version: '3.8'

services:
    listoor:
        image: ghcr.io/0xmichalis/listoor:latest
        pull_policy: always
        container_name: listoor
        env_file:
            - .env
        volumes:
            - ./data/collections.json:/app/data/collections.json
        restart: unless-stopped
