# .github/workflows/build-and-push.yml
name: Build and Push Docker Image

on:
  push:
    branches: [main]  # Trigger on main branch pushes
  workflow_dispatch:  # Manual trigger

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Check formatting
        run: yarn format:check

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Required to push to GHCR
      id-token: write  # Required for OIDC auth (optional for GHCR)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/listoor
          docker build -t $IMAGE_NAME:latest .

      - name: Push to GHCR
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/listoor
          docker push $IMAGE_NAME:latest

